{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "platform-chart.fullname" . }}-api
  labels:
    {{- include "platform-chart.componentLabels" (dict "component" "api" "Release" .Release "Chart" .Chart "Values" .Values) | nindent 4 }}
spec:
  selector:
    {{- include "platform-chart.componentSelectorLabels" (dict "component" "api" "Release" .Release "Chart" .Chart "Values" .Values) | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
{{- end }}
