{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "platform-chart.fullname" . }}-redis
  labels:
    {{- include "platform-chart.componentLabels" (dict "component" "redis" "Release" .Release "Chart" .Chart "Values" .Values) | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "platform-chart.componentSelectorLabels" (dict "component" "redis" "Release" .Release "Chart" .Chart "Values" .Values) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "platform-chart.componentLabels" (dict "component" "redis" "Release" .Release "Chart" .Chart "Values" .Values) | nindent 8 }}
    spec:
      # imagem oficial roda como UID 999 por padrão.
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          ports:
            - name: redis
              containerPort: 6379
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
      volumes:
        - name: tmp
          emptyDir: {}
{{- end }}
